service: urban-eureka

provider:
  name: aws
  stage: dev
  runtime: java8
  region: us-east-1
  timeout: 30
  vpc:
    securityGroupIds:
      - sg-008ad472d19399f21
    subnetIds:
      - subnet-39c1ff40
        subnet-6e491225
        subnet-fe5159a4
        subnet-40a2226b

package:
  artifact: 'target/${self:service}-${self:provider.stage}.jar'

functions:
  newUnidade:
    handler: com.serverless.handlers.UnidadeHandler::put
    events:
      - http:
          path: /unidade/{name}/{type}/{city}/{address}/{latitude}/{longitude}/{url}/{avatar}/{active}/{sescId}
          method: put
  saveUnidade:
    handler: com.serverless.handlers.UnidadeHandler::post
    events:
      - http:
          path: /unidade/{id}/{name}/{type}/{city}/{address}/{latitude}/{longitude}/{url}/{avatar}/{active}/{sescId}
          method: post
  getUnidade:
    handler: com.serverless.handlers.UnidadeHandler::get
    events:
      - http:
          path: /unidade/{id}
          method: get
  deleteUnidade:
    handler: com.serverless.handlers.UnidadeHandler::delete
    events:
      - http:
          path: /unidade/{id}
          method: delete
